name: HytraliumAPI
version: '${project.version}'
softdepend: [ LuckPerms, TAB ]
authors:
  - Hytralium
  - AslowBridger_
main: me.hytralium.hytraliumapi.HytraliumAPI
commands:
  testsub:
    description: test